### ISSUE TITLE
Add Python decouple

### ISSUE THREAD

**Issue by heitordeep** [ResXBocchi/Linkedin-Spider#1]
Olá, tudo bom? Primeiramente achei massa seu código, se me permite acho interessante ajustar algumas coisas para ficar mais bacana.

Algumas dicas de mudança:

1 - Mude a variável driver no arquivo **linkedin_spider.py**:
     
     driver = webdriver.Chrome(executable_path=parameters.driver_path)

2 - Crie um arquivo .env com os seguintes parâmetros:

     EMAIL=
     PASSWORD=
     DRIVER_PATH=C:\Program Files\Google\Chrome\Application\chromedriver

3 - dentro do arquivo parameters.py, add: 

    from decouple import config
    search_query = 'site:linkedin.com/in AND "python developer" AND "Alagoas"'
    result_file = 'output.csv'  # Não está sendo usado

    username = config('EMAIL')
    password = config('PASSWORD')
    driver_path = config('DRIVER_PATH')

4 - Corrija o requirements, acredito que não precisamos instalar diversas bibliotecas: 
- parsel==1.6.0
  python-decouple==3.3
  selenium==3.141.0

5 - Por último, adicione o **.gitignore** para remover alguns arquivos/diretórios que não são "úteis" no projeto:

    __pycache__
    .pyc
    .cache
    debug.log
    .env

OBS: Não consegui abrir um PR, acredito que não tenho permissão :smile: 

Espero ter te ajudado e que seu projeto evolua :rocket:

**Comment by r3sx1337** [comment]
Muito obrigado pelas excelentes melhorias!
